CREATE DATABASE poucevert; 
USE poucevert; 

CREATE TABLE users(
 id INT AUTO_INCREMENT PRIMARY KEY,
 nom VARCHAR(255) NOT NULL,
 prenom VARCHAR(255) NOT NULL,
 pseudo VARCHAR(255) NOT NULL,
 email VARCHAR(255) NOT NULL,
 password VARCHAR(255) NOT NULL,
 subscribed DATETIME DEFAULT NOW()	
); 
